### ISSUE TITLE
Error with labelling on Mercury

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1206]
Report from Alex @ NCMNS

•	On Mercury, labelling of surface features shows up, changing font size gives an error, changing label size works well until an upper limit, changing label minimum height causes an error.

**Comment by GPayne** [comment]
I don't see these problems anymore. I believe these problems were fixed with issue #1209.

**Comment by WeirdRubberDuck** [comment]
Reopening, as I am still observing this issue. Steps to reproduce: 
1, Go to Mercury and enable the labels 
2. Make sure they are visible, then try to increase the label font size to something pretty large, such as 100
3. See your log being filled with errors

![image](https://user-images.githubusercontent.com/8808894/111120527-bcc5b300-856b-11eb-948e-db2c63403a72.png)

Also, after the error has happened it seem like the scriptlog gets broken somehow. For example, trying to use the arrow buttons in the time UI to increase the delta time step size results in the error "Could not open file 'D:\dev\OpenSpace\logs\ScriptLog.txt' for logging scripts"

**Comment by alexanderbock** [comment]
Last time I saw this, there was an exception in the font rendering, leaving the font file opened.   Windows has a limited number of files it can keep opened so when OpenSpace then tries to write something to the scriptlog, that file opening fails since the maximum number of opened files has been reached.   Error should be in the font.cpp in Ghoul where the glyphs are loaded.  I did some change there recently.  I'm assuming someone isn't checking whether a specific glyph exists before rendering it

**Comment by WeirdRubberDuck** [comment]
A hotfix for this issue was added in a40e110fe9f662613dd2b4f53033a65d243f13f3, but it does not actually solve the problem with the font loading. It just prevents the problem from occurring during runtime 

I suggest we close this issue and create another that is focused on the font loading error, as it is not specific for Mercury. (Updating the minimum height and text size does not lead to any errors)
