### ISSUE TITLE
Startup Problem M6000 OpenGL rendering on 8K Screen

### ISSUE THREAD

**Issue by pedrocolon93** [OpenSpace/OpenSpace#220]
Hi there again.  I'm trying to get this up and running on an 8k screen.  I'm using a Quadro M6000.

When I start the openspace.exe it just crashes.  I suspect it has something to do with OpenGL.  The machine is running the latest Nvidia driver.  

Here is the output.  
```
FileSystem (Info) : Set temporary path ${TEMPORARY} to C:\Users\8Kdemo\AppData\Local\Temp\
OpenSpaceEngine (Debug) Initialize FileSystem
OpenSpaceEngine (Debug) Creating OpenSpaceEngine
TransformationManager (Warning) Kameleon module needed for transformations with dynamic frames
OpenSpaceEngine (Debug) Finding configuration
OpenSpaceEngine (Info)  Configuration Path: 'E:\OpenSpace\openspace.cfg'
OpenSpaceEngine (Debug) Loading configuration from disk
Lua (Debug)     Creating Lua state
Lua (Debug)     Open libraries
ConfigurationManager (Debug)    Registering path ${CACHE}: ${BASE_PATH}/cache
ConfigurationManager (Debug)    Registering path ${CONFIG}: ${BASE_PATH}/config
ConfigurationManager (Debug)    Registering path ${DOCUMENTATION}: ${BASE_PATH}/documentation
ConfigurationManager (Debug)    Registering path ${FONTS}: ${OPENSPACE_DATA}/fonts
ConfigurationManager (Debug)    Registering path ${MODULES}: ${BASE_PATH}/modules
ConfigurationManager (Debug)    Registering path ${OPENSPACE_DATA}: ${BASE_PATH}/data
ConfigurationManager (Debug)    Registering path ${SCENE}: ${OPENSPACE_DATA}/scene
ConfigurationManager (Debug)    Registering path ${SCRIPTS}: ${BASE_PATH}/scripts
ConfigurationManager (Debug)    Registering path ${SGCT}: ${BASE_PATH}/config/sgct
ConfigurationManager (Debug)    Registering path ${SHADERS}: ${BASE_PATH}/shaders
ConfigurationManager (Debug)    Registering path ${SPICE}: ${OPENSPACE_DATA}/spice
ConfigurationManager (Debug)    Registering path ${TESTDIR}: ${BASE_PATH}/tests
OpenSpace Version (Info)        0.6.0 (prerelease-11 (AGU))
ModuleEngine (Debug)    Registering module 'Base'
OpenSpaceModule (Debug) Registering module path: ${MODULE_BASE}: E:\OpenSpace\modules\base
ModuleEngine (Debug)    Registering module 'Debugging'
OpenSpaceModule (Debug) Registering module path: ${MODULE_DEBUGGING}: E:\OpenSpace\modules\debugging
ModuleEngine (Debug)    Registering module 'Space'
OpenSpaceModule (Debug) Registering module path: ${MODULE_SPACE}: E:\OpenSpace\modules\space
ModuleEngine (Debug)    Registering module 'NewHorizons'
OpenSpaceModule (Debug) Registering module path: ${MODULE_NEWHORIZONS}: E:\OpenSpace\modules\newhorizons
ModuleEngine (Debug)    Registering module 'OnScreenGUI'
OpenSpaceModule (Debug) Registering module path: ${MODULE_ONSCREENGUI}: E:\OpenSpace\modules\onscreengui
ModuleEngine (Debug)    Registering module 'ToyVolume'
OpenSpaceModule (Debug) Registering module path: ${MODULE_TOYVOLUME}: E:\OpenSpace\modules\toyvolume
/OpenSpaceEngine (Debug)        Determining SGCT configuration file
main (Info)     Detected OpenGL version: 4.5
main (Debug)    Creating SGCT Engine
SGCT (Info)     Parsing arguments...
SGCT (Info)     Done
main (Debug)    Initialize SGCT Engine
SGCT (Info)     SGCT ver 2.7.3
SGCT (Info)     ReadConfig: Parsing XML config 'E:\OpenSpace\config\sgct\single.xml'...
SGCT (Info)     ReadConfig: Display swap interval is set to 0.
SGCT (Info)     SGCTNode: Setting address to localhost
SGCT (Info)     SGCTNode: Setting sync port to 20401
SGCT (Info)     FXAA status: disabled for window 0
SGCT (Info)     SGCTWindow: Setting stereo mode to 'none' for window 0.
SGCT (Info)     Viewport: Adding planar projection FOV down=16.875000 left=30.000000 right=30.000000 up=16.875000
SGCT (Info)     Viewplane lower left coords: -5.773502 -3.033467 -10.000000
SGCT (Info)     Viewplane upper left coords: -5.773502 3.033467 -10.000000
SGCT (Info)     Viewplane upper right coords: 5.773502 3.033467 -10.000000

SGCT (Info)     Adding viewport (total 1)
SGCT (Info)     ReadConfig: Config file 'E:/OpenSpace/config/sgct/single.xml' read successfully!
SGCT (Info)     ReadConfig: Number of nodes in cluster: 1
SGCT (Info)             Node(0) address: localhost [20401]
SGCT (Info)     NetworkManager: Initiating network API...
SGCT (Info)     NetworkManager: Getting host info...
SGCT (Info)     NetworkManager: This computer is the network server.
SGCT (Info)     Matching ip address to find node in configuration...
SGCT (Info)     NetworkManager: Running in cluster mode as node 0
SGCT (Info)     NetworkManager: Initiating network connection 0 at port 20500.
SGCT (Info)     NetworkManager: Cluster sync is set to loose
SGCT (Info)     Waiting for client to connect to connection 0 (port 20500)...
SGCT (Info)     Using GLFW version 3.1.1
ROSSGCT (Info)  Using GLEW 1.12.0.
SGCT (Info)     OpenGL error: GL_INVALID_ENUM
SGCT (Info)     GLEW init triggered an OpenGL error.
SGCT (Info)     OpenGL version 4.5.0 core profile
SGCT (Info)     Vendor: NVIDIA Corporation
SGCT (Info)     Renderer: Quadro M6000/PCIe/SSE2
SGCT (Info)     Statistics: Generating VAOs:
SGCT (Info)             1
SGCT (Info)             2
SGCT (Info)             3

SGCT (Info)     Statistics: Generating VBOs:
SGCT (Info)             1
SGCT (Info)             2
SGCT (Info)             3

SGCT (Info)
---- Calling init callback ----

```

**Comment by alexanderbock** [comment]
Does it work if you run it in 4K?

**Comment by pedrocolon93** [comment]
I'll try this out tomorrow to see.

**Comment by pedrocolon93** [comment]
I tried with the single_4k configuration and it crashes with the same log.

**Comment by pedrocolon93** [comment]
Also tried making a single 8k configuration:

```xml
<?xml version="1.0" ?>
<Cluster masterAddress="localhost" externalControlPort="20500">
    <Settings>
        <Display swapInterval="0" />
    </Settings>
    <Node address="localhost" port="20401">
        <Window fullScreen="true"  fxaa="false" numberOfSamples="4" name="OpenSpace">
            <Stereo type="none" />
            <Size x="1280" y="720" />
            <Res x="7680" y="4320" />
            <Pos x="50" y="50" />
            <Viewport>
                <Pos x="0.0" y="0.0" />
                <Size x="1.0" y="1.0" />
                <PlanarProjection>
                    <FOV down="16.875" left="30.0" right="30.0" up="16.875" />
                    <Orientation heading="0.0" pitch="0.0" roll="0.0" />
                </PlanarProjection>
            </Viewport>
        </Window>
    </Node>
    <User eyeSeparation="0.065">
        <Pos x="0.0" y="0.0" z="0.0" />
    </User>
</Cluster>


```
Also crashes with the SGCT (Info)     OpenGL error: GL_INVALID_ENUM
error.

Let me know what I can try.

**Comment by alexanderbock** [comment]
This looks strange..  I just pushed a new change to the `develop` branch (a6c422c38e8000995ed62c4576271ec42b6e35ed) that will print out a bit more information about the initialization.  Could you try that out?

Further, you mentioned that you have a 8k monitor, so you can just write 
```xml
            <Size x="7680" y="4320" />
```

instead of
```
            <Size x="1280" y="720" />
            <Res x="7680" y="4320" />
```

The first one will generate a window with the resolution; the second one will create a window of size 1280x720 with the internal resolution of 8k

**Comment by pedrocolon93** [comment]
I'll check this tomorrow, the lab is closed today!

**Comment by pedrocolon93** [comment]
Hi,

I just tried this, and it seems to have the same error.  It may be a problem with SGCT.  

```
FileSystem (Info) : Set temporary path ${TEMPORARY} to C:\Users\8Kdemo\AppData\Local\Temp\
OpenSpaceEngine (Debug) Initialize FileSystem
OpenSpaceEngine (Debug) Creating OpenSpaceEngine
TransformationManager (Warning) Kameleon module needed for transformations with dynamic frames
OpenSpaceEngine (Debug) Finding configuration
OpenSpaceEngine (Info)  Configuration Path: 'C:\Users\8Kdemo\Desktop\OpenSpace\openspace.cfg'
OpenSpaceEngine (Debug) Loading configuration from disk
Lua (Debug)     Creating Lua state
Lua (Debug)     Open libraries
ConfigurationManager (Debug)    Registering path ${CACHE}: ${BASE_PATH}/cache
ConfigurationManager (Debug)    Registering path ${CONFIG}: ${BASE_PATH}/config
ConfigurationManager (Debug)    Registering path ${DOCUMENTATION}: ${BASE_PATH}/documentation
ConfigurationManager (Debug)    Registering path ${FONTS}: ${OPENSPACE_DATA}/fonts
ConfigurationManager (Debug)    Registering path ${MODULES}: ${BASE_PATH}/modules
ConfigurationManager (Debug)    Registering path ${OPENSPACE_DATA}: ${BASE_PATH}/data
ConfigurationManager (Debug)    Registering path ${SCENE}: ${OPENSPACE_DATA}/scene
ConfigurationManager (Debug)    Registering path ${SCRIPTS}: ${BASE_PATH}/scripts
ConfigurationManager (Debug)    Registering path ${SGCT}: ${BASE_PATH}/config/sgct
ConfigurationManager (Debug)    Registering path ${SHADERS}: ${BASE_PATH}/shaders
ConfigurationManager (Debug)    Registering path ${SPICE}: ${OPENSPACE_DATA}/spice
ConfigurationManager (Debug)    Registering path ${TESTDIR}: ${BASE_PATH}/tests
OpenSpace Version (Info)        0.6.0 (prerelease-11 (AGU))
ModuleEngine (Debug)    Registering module 'Base'
OpenSpaceModule (Debug) Registering module path: ${MODULE_BASE}: C:\Users\8Kdemo\Desktop\OpenSpace\modules\base
ModuleEngine (Debug)    Registering module 'Debugging'
OpenSpaceModule (Debug) Registering module path: ${MODULE_DEBUGGING}: C:\Users\8Kdemo\Desktop\OpenSpace\modules\debugging
ModuleEngine (Debug)    Registering module 'Space'
OpenSpaceModule (Debug) Registering module path: ${MODULE_SPACE}: C:\Users\8Kdemo\Desktop\OpenSpace\modules\space
ModuleEngine (Debug)    Registering module 'NewHorizons'
OpenSpaceModule (Debug) Registering module path: ${MODULE_NEWHORIZONS}: C:\Users\8Kdemo\Desktop\OpenSpace\modules\newhorizons
ModuleEngine (Debug)    Registering module 'OnScreenGUI'
OpenSpaceModule (Debug) Registering module path: ${MODULE_ONSCREENGUI}: C:\Users\8Kdemo\Desktop\OpenSpace\modules\onscreengui
ModuleEngine (Debug)    Registering module 'ToyVolume'
OpenSpaceModule (Debug) Registering module path: ${MODULE_TOYVOLUME}: C:\Users\8Kdemo\Desktop\OpenSpace\modules\toyvolume
OpenSpaceEngine (Debug) Determining SGCT configuration file
main (Info)     Detected OpenGL version: 4.5
main (Debug)    Creating SGCT Engine
SGCT (Info)     Parsing arguments...
SGCT (Info)     Done
main (Debug)    Initialize SGCT Engine
SGCT (Info)     SGCT ver 2.7.3
SGCT (Info)     ReadConfig: Parsing XML config 'C:\Users\8Kdemo\Desktop\OpenSpace\config\sgct\single.xml'...
SGCT (Info)     ReadConfig: Display swap interval is set to 0.
SGCT (Info)     SGCTNode: Setting address to localhost
SGCT (Info)     SGCTNode: Setting sync port to 20401
SGCT (Info)     FXAA status: disabled for window 0
SGCT (Info)     SGCTWindow: Setting stereo mode to 'none' for window 0.
SGCT (Info)     Viewport: Adding planar projection FOV down=16.875000 left=30.000000 right=30.000000 up=16.875000
SGCT (Info)     Viewplane lower left coords: -5.773502 -3.033467 -10.000000
SGCT (Info)     Viewplane upper left coords: -5.773502 3.033467 -10.000000
SGCT (Info)     Viewplane upper right coords: 5.773502 3.033467 -10.000000

SGCT (Info)     Adding viewport (total 1)
SGCT (Info)     ReadConfig: Config file 'C:/Users/8Kdemo/Desktop/OpenSpace/config/sgct/single.xml' read successfully!
SGCT (Info)     ReadConfig: Number of nodes in cluster: 1
SGCT (Info)             Node(0) address: localhost [20401]
SGCT (Info)     NetworkManager: Initiating network API...
SGCT (Info)     NetworkManager: Getting host info...
SGCT (Info)     NetworkManager: This computer is the network server.
SGCT (Info)     Matching ip address to find node in configuration...
SGCT (Info)     NetworkManager: Running in cluster mode as node 0
SGCT (Info)     NetworkManager: Initiating network connection 0 at port 20500.
SGCT (Info)     NetworkManager: Cluster sync is set to loose
SGCT (Info)     Using GLFW version 3.1.1
SGCT (Info)     Waiting for client to connect to connection 0 (port 20500)...
SGCT (Info)     Using GLEW 1.12.0.
SGCT (Info)     OpenGL error: GL_INVALID_ENUM
SGCT (Info)     GLEW init triggered an OpenGL error.
SGCT (Info)     OpenGL version 4.5.0 core profile
SGCT (Info)     Vendor: NVIDIA Corporation
SGCT (Info)     Renderer: Quadro M6000/PCIe/SSE2
SGCT (Info)     Statistics: Generating VAOs:
SGCT (Info)             1
SGCT (Info)             2
SGCT (Info)             3

SGCT (Info)     Statistics: Generating VBOs:
SGCT (Info)             1
SGCT (Info)             2
SGCT (Info)             3

SGCT (Info)
---- Calling init callback ----
main (Debug)    Initializing OpenSpace Engine
OpenSpaceEngine (Debug) Clearing all Windows
OpenSpaceEngine (Debug) Adding system components
```

**Comment by pedrocolon93** [comment]
A small update.  Apparently the problem was with GLEW which if you use the hint, it may fail with the initialization (apparently this occurs even with glewExperimental enabled.)

Commenting these lines out in Engine.cpp in sgct. fixes the initialization error, however it still fails to start and crashes.  

```

	case OpenGL_4_5_Core_Profile:
	{
		//glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
		//glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
#if __APPLE__
		glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
#endif
		//glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
		//glewExperimental = true; // Needed for core profile
		mGLSLVersion.assign("#version 450 core");
	}
```
The error can be found here:
https://github.com/go-gl/glfw/issues/50

I'm guessing that after that it simply doesnt get the correct version to start up or something.

**Comment by pedrocolon93** [comment]
Round 3! I stepped into the application with the debugger and eventually found the problem.  Apparently Ghoul calls in the systemcapabilitiescomponent.cpp the function initializeWMI().  There is a function in this function that apparently is executed when the application is run the first time and does not need to be reexecuted after.  Ghoul is executing this function and it causes a crash.  

the workaround right now is in the aforementioned file find the lines in initializeWMI:
```
    /*hRes = CoInitializeSecurity(
        NULL, 
        -1,                          // COM authentication
        NULL,                        // Authentication services
        NULL,                        // Reserved
        RPC_C_AUTHN_LEVEL_DEFAULT,   // Default authentication 
        RPC_C_IMP_LEVEL_IMPERSONATE, // Default Impersonation  
        NULL,                        // Authentication info
        EOAC_NONE,                   // Additional capabilities 
        NULL                         // Reserved
    `);*/
```
and comment them out as shown.  This then lets the entire thing run through and render.  I'll write back if theres any problems with this.

**Comment by pedrocolon93** [comment]
I'm closing this.

**Comment by alexanderbock** [comment]
Sorry for not answering earlier, the `CoinitializeSecurity` is a duplicate of #245 .  Did you run into other trouble afterwards?

**Comment by pedrocolon93** [comment]
Hey, I can't get some scenes to start correctly after this patch.  I'm assuming it has something to do with the data and not the fix.
